name=usa
description="USA CDC dataset on variants"
sources="https://public.tableau.com/views/WeightedStateVariantTable/StateVBMTable.csv?%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Aembed=true&%3Alanguage=en-US&:embed=y&:showVizHome=n&:apiID=host0#navType=0&navSrc=Parse   usa.csv"
build() {
    :
}
